# Generated by Django 5.0.2 on 2024-09-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_teacher_updatedat_remove_teacher_user_and_more'),
        ('students', '0005_alter_studentparent_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classteacher_teacherid', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
