# Generated by Django 5.0.2 on 2024-09-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_classteacher_teacher_alter_task_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='classid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.class'),
        ),
    ]
