# Generated by Django 5.0.2 on 2024-09-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classschedule_teacher_alter_marks_teacherid_and_more'),
        ('students', '0008_medicalinfo_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_section',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classschedule'),
        ),
    ]
