# Generated by Django 5.0.2 on 2024-10-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_rename_teacher_clssec_id_classteacher_classteacherid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='classcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(max_length=20),
        ),
    ]
