# Generated by Django 5.0.2 on 2024-10-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_classteacher_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10, null=True),
        ),
    ]
