# Generated by Django 5.0.2 on 2024-11-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schoolid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.school'),
        ),
        migrations.AlterField(
            model_name='section',
            name='classid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='students.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classid', to='students.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='clssectionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_clssectionid', to='students.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_schoolid', to='students.school'),
        ),
    ]
