# Generated by Django 5.0.2 on 2024-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('empfname', models.CharField(max_length=60)),
                ('emplname', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('employee_role', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('ntsid', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('nts_fname', models.CharField(max_length=255)),
                ('nts_lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('tfname', models.CharField(max_length=255)),
                ('tlname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
