# Generated by Django 5.0.2 on 2024-09-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_school', to='students.school'),
        ),
        migrations.AddField(
            model_name='nonteachingstaff',
            name='schoolempid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updatedat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_schoolempid', to='employees.employee'),
        ),
    ]
