# Generated by Django 5.0.2 on 2024-09-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='updatedat',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empfname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emplname',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NonTeachingStaff',
        ),
    ]
