# Generated by Django 5.0.2 on 2024-09-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classschedule_teacher_alter_marks_teacherid_and_more'),
        ('employees', '0004_remove_teacher_updatedat_remove_teacher_user_and_more'),
        ('students', '0006_alter_classteacher_teacher_alter_task_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
