# Generated by Django 5.0.2 on 2024-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contactno',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
