# Generated by Django 5.0.2 on 2024-09-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_emailid_employee_email_and_more'),
        ('students', '0007_alter_section_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_school', to='students.school'),
        ),
    ]
