# Generated by Django 5.0.2 on 2024-09-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_schoolid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_role',
        ),
    ]
