# Generated by Django 5.0.2 on 2024-09-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('employees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='employees.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='clssectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.school'),
        ),
        migrations.AddField(
            model_name='marks',
            name='clssectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.section'),
        ),
        migrations.AddField(
            model_name='marks',
            name='examid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.exam'),
        ),
        migrations.AddField(
            model_name='marks',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.teacher'),
        ),
        migrations.AddField(
            model_name='period',
            name='clssectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.section'),
        ),
        migrations.AddField(
            model_name='period',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.teacher'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.period'),
        ),
        migrations.AddField(
            model_name='result',
            name='examid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.exam'),
        ),
        migrations.AddField(
            model_name='result',
            name='marks_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.marks'),
        ),
        migrations.AddField(
            model_name='result',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='classid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.class'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.teacher'),
        ),
        migrations.AddField(
            model_name='period',
            name='subject_teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subjectteacher'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
    ]
