# Generated by Django 5.0.2 on 2024-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classschedule_teacher_alter_marks_teacherid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
