# Generated by Django 5.0.2 on 2024-10-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_subject_code'),
        ('students', '0011_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.section'),
        ),
    ]
