# Generated by Django 5.0.2 on 2024-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classschedule_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Book_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
