# Generated by Django 5.0.2 on 2024-10-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_period_subject_teacher_id_and_more'),
        ('students', '0016_attendance_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='students.class'),
        ),
    ]
