# Generated by Django 5.0.2 on 2024-10-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_subject_classid'),
        ('employees', '0009_remove_employee_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacher',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_teachers', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_preferences', to='employees.employee'),
        ),
    ]
