# Generated by Django 5.0.2 on 2024-10-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_subjectteacher_subjectid_and_more'),
        ('employees', '0009_remove_employee_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjectteacher_set', to='employees.employee'),
        ),
    ]
