# Generated by Django 5.0.2 on 2024-10-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_subjectteacher_unique_together_and_more'),
        ('employees', '0009_remove_employee_employee_role'),
        ('students', '0016_attendance_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.class'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='clssectionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectteacher_set', to='students.section'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectteacher_set', to='employees.employee'),
        ),
    ]
