# Generated by Django 5.0.2 on 2024-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
