# Generated by Django 5.0.2 on 2024-10-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
    ]
