# Generated by Django 5.0.2 on 2024-10-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_timetable_academic_year'),
        ('students', '0016_attendance_session_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('subjectid', 'clssectionid')},
        ),
    ]
